import type { Metadata } from "next";
import { Monomaniac_One } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header/HeaderMain/Header";
import Sidebar from "@/components/Sidebar/Sidebar";

const monomaniac = Monomaniac_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "G-Skin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${monomaniac.className} bg-black text-white`}>
        {/* Вся страница — вертикально */}
        <div className="flex flex-col min-h-screen">
          {/* Header — сверху */}
          <Header />

          {/* Контент — Sidebar + Main */}
          <div className="flex flex-1">
            <Sidebar />
            <main className="flex-1">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
