import type { Metadata } from "next";
import { Monomaniac_One } from "next/font/google";
import "./globals.css";

import Header from "../components/Header";

const monomaniac = Monomaniac_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "G-Skin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monomaniac.className}>
        <Header />
        <main className="min-h-screen">{children}</main>
        {/* <Footer />  */}
      </body>
    </html>
  );
}
